# Site settings
title: Xingchen Blog
SEOTitle: 星辰的博客 | Xingchen Blog
header-img: img/back-full.jpeg
email: Xingchen.luo@mail.mcgill.com
description: "A man is least himself when he talks in his own person. Give him a mask and he will tell you the truth."
keyword: "XC, XC Blog, 星辰的博客, XingchenLuo, 骆星辰, Apple, iPhone"
url: "http://tiger7789.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' sif your blog hosted on 'host/blog'
github_repo: "https://github.com/tiger7789/tiger7789.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "You have to believe in yourself when no one else does – that makes you a winner right there!"
sidebar-avatar: /img/self-side.jpeg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     
github_username:    tiger7789
#facebook_username:  
#jianshu_username:   
#twitter_username:   
weixin_username:  /img/self-side.jpeg  



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
disqus_username: samluo1216



# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-G-BB5R5C2HCJ'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "Cassiel.H's Blog",
        href: "https://cassiel-h.github.io/"
    },{
        title: "My Linkedin",
        href: "https://www.linkedin.com/in/xingchen-luo-1216lxc/"
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Tesla",
        href: "https://tesla.com/"
    },{
    title: "Yahoo Finance",
        href: "https://ca.finance.yahoo.com/"
    }
]
